name: Deploy to Production

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'
  
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Type check
        working-directory: ./backend
        run: npm run typecheck

      - name: Build
        working-directory: ./backend
        run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        run: |
          echo "🚀 Deploying to Railway..."
          echo "Railway will automatically deploy from GitHub integration"
          echo "Or use Railway CLI: railway up"

      - name: Health Check
        run: |
          echo "⏳ Waiting 30 seconds for deployment..."
          sleep 30
          echo "🏥 Checking health endpoint..."
          # Replace with your actual deployment URL
          # curl -f https://your-app.railway.app/health || exit 1

      - name: Notify Success
        if: success()
        run: |
          echo "✅ Deployment successful!"
          echo "🌐 App is live at your deployment URL"

      - name: Notify Failure
        if: failure()
        run: |
          echo "❌ Deployment failed!"
          echo "Check logs above for details"
